# Generated by Django 4.1.2 on 2022-10-18 11:13

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(default='123', max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=50)),
                ('enrollment_type', models.CharField(blank=True, max_length=15, null=True)),
                ('date_administered', models.DateField(blank=True, default='2022-09-20', null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.CharField(blank=True, max_length=12, null=True)),
                ('sex', models.IntegerField(blank=True, default=0, null=True)),
                ('date_of_birth', models.DateField(blank=True, default='2022-09-20', null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=20, null=True)),
                ('educational_attainment', models.CharField(blank=True, max_length=50, null=True)),
                ('is_pwd', models.IntegerField(blank=True, default=0, null=True)),
                ('is_4ps_beneficiary', models.IntegerField(blank=True, default=0, null=True)),
                ('is_ip', models.IntegerField(blank=True, default=0, null=True)),
                ('main_livelihood', models.CharField(blank=True, max_length=50, null=True)),
                ('livelihood_product', models.CharField(blank=True, max_length=50, null=True)),
                ('laborer_activity', models.CharField(blank=True, max_length=50, null=True)),
                ('fishing_activity', models.CharField(blank=True, max_length=50, null=True)),
                ('involvement_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ownership_document', models.TextField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
