# Generated by Django 4.1.2 on 2022-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ownership_document_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='signature_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
