# Generated by Django 4.1.2 on 2022-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigo_app', '0002_account_ownership_document_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fishing_activity',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='involvement_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='laborer_activity',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='livelihood_product',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='main_livelihood',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='signature',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
