# Generated by Django 4.1.2 on 2022-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigo_app', '0003_alter_account_fishing_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ownership_document',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
