# Generated by Django 4.1.2 on 2022-11-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigo_app', '0004_alter_account_ownership_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='civil_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_administered',
            field=models.DateField(blank=True, default='2022-09-20'),
        ),
        migrations.AlterField(
            model_name='account',
            name='educational_attainment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='enrollment_type',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='fishing_activity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='involvement_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_4ps_beneficiary',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_ip',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_pwd',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='laborer_activity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='livelihood_product',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='main_livelihood',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='ownership_document',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='ownership_document_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='place_of_birth',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='signature_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
