# Generated by Django 4.1.2 on 2022-11-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigo_app', '0005_alter_account_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
